---
# tasks file for config-k8s-master
- name: "Creating Kubernetes repo"
  yum_repository:
          name: "kube"
          description: "kubernetes repository"
          baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
          enabled: 1
          gpgcheck: 1
          repo_gpgcheck: 1
          gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"


- name: "Downloading Kubeadm"
  package:
          name: "kubeadm"
          state: present

- name: "Starting Kubelet"
  service:
          name: "kubelet"
          state: started

- name: "Downloading Docker"
  package:
          name: "docker"
          state: present

- name: "Starting Docker"
  service:
          name: "docker"
          state: started

- name: "Copying drivers file"
  copy:
          src: daemon.json
          dest: /etc/docker/daemon.json

- name: "Restarting Docker"
  service:
          name: "docker"
          state: restarted

- name: "Downloading IProute-tc"
  package:
          name: "iproute-tc"
          state: present

- name: "Uploading IProute file"
  copy:
          src: k8s.conf
          dest: /etc/sysctl.d/k8s.conf

- name: "Starting service"
  shell: "sysctl --system"

- name: "Initializing Kubeadm"
  shell: "kubeadm init --pod-network-cidr={{ ip_range }} --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"
          
- name: "Setting it as master node-1"
  file:
           path: "/root/.kube"
           state: directory

- name: "Setting it as master node-2"
  copy:
           src: "/etc/kubernetes/admin.conf" 
           dest: "/root/.kube/config"
           remote_src: yes
           owner: root

- name: "Configuring kube-flannel"
  template:
           src: kube-flannel.yml
           dest: /root/

- name: "Running kube-flannel"
  shell: "kubectl apply -f /root/kube-flannel.yml"

